### PR TITLE
Improved channels initialization

### PR DESCRIPTION
**Pull request by LeonardoRosaa**

### CODE REVIEW

**Comment by LeonardoRosaa** [comment]
@fryette or @geweald  - can you review this PR? :)

**Comment by fryette** [comment]
I'm not a author of this repo.
Need to wait @geweald

**Comment by geweald** [comment]
Hey @LeonardoRosaa @fryette, sorry, but I no longer have the ability or capacity to work on onfido plugin or to even test your PRs, I can give you edit permissions to merge if you like or I can discontinue this package and you can create & maintain on your own, what do you think?

**Comment by LeonardoRosaa** [comment]
> Hey @LeonardoRosaa @fryette, sorry, but I no longer have the ability or capacity to work on onfido plugin or to even test your PRs, I can give you edit permissions to merge if you like or I can discontinue this package and you can create & maintain on your own, what do you think?

Okay, I can help maintain this project :)

**Review by geweald — APPROVED** [review]

**Review by geweald — APPROVED** [review]

**Pull request merged**
